### ISSUE TITLE
Huge errors and warning in examples/java/BasicMap

### ISSUE THREAD

**Issue by dkati** [googlemaps-samples/android-samples#1474]
```
2024-02-13 13:21:06.654  3070-3160  GoogleApiManager        com.example.mapdemo.gms              E  Failed to get service from broker. 
                                                                                                    java.lang.SecurityException: Unknown calling package name 'com.google.android.gms'.
                                                                                                    	at android.os.Parcel.createExceptionOrNull(Parcel.java:3069)
                                                                                                    	at android.os.Parcel.createException(Parcel.java:3053)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:3036)
                                                                                                    	at android.os.Parcel.readException(Parcel.java:2978)
                                                                                                    	at m.cqy.q(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:180)
                                                                                                    	at m.cpk.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:54)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
2024-02-13 13:21:06.674  3070-3215  ProxyAndro...gerBackend com.example.mapdemo.gms              W  Too many Flogger logs received before configuration. Dropping old logs.
2024-02-13 13:21:06.686  3070-3161  MobStoreFlagStore       com.example.mapdemo.gms              W  Unable to update local snapshot for com.google.android.gms.maps#com.google.android.gms, may result in stale flags.
                                                                                                    java.util.concurrent.ExecutionException: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                                    	at m.gua.s(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:21)
                                                                                                    	at m.gua.get(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
                                                                                                    	at m.gwy.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:2)
                                                                                                    	at m.gvt.h(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:10)
                                                                                                    	at m.fgk.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.fgr.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:5)
                                                                                                    	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:487)
                                                                                                    	at java.util.concurrent.FutureTask.run(FutureTask.java:264)
                                                                                                    	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:307)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                    	at java.lang.Thread.run(Thread.java:1012)
                                                                                                    Caused by: m.few: 17: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                                    	at m.fey.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:13)
                                                                                                    	at m.gtx.e(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:3)
                                                                                                    	at m.gtz.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:139)
                                                                                                    	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.gua.q(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.gua.k(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:96)
                                                                                                    	at m.gua.n(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:19)
                                                                                                    	at m.fbx.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:35)
                                                                                                    	at m.cyi.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:12)
                                                                                                    	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.cyj.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:12)
                                                                                                    	at m.cyr.b(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:36)
                                                                                                    	at m.cyv.g(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:20)
                                                                                                    	at m.cyf.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:83)
                                                                                                    	at m.guz.execute(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:1)
                                                                                                    	at m.cyg.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:8)
                                                                                                    	at m.cyr.b(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:36)
                                                                                                    	at m.cys.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:25)
                                                                                                    	at m.coj.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:7)
                                                                                                    	at m.cpi.s(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:48)
                                                                                                    	at m.cpi.f(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:10)
                                                                                                    	at m.cpi.j(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:177)
2024-02-13 13:21:06.688  3070-3161  MobStoreFlagStore       com.example.mapdemo.gms              W  	at m.cpi.i(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:2)
                                                                                                    	at m.cpk.run(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:82)
                                                                                                    	at android.os.Handler.handleCallback(Handler.java:958)
                                                                                                    	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                                                                    	at android.os.Looper.loopOnce(Looper.java:230)
                                                                                                    	at android.os.Looper.loop(Looper.java:319)
                                                                                                    	at android.os.HandlerThread.run(HandlerThread.java:67)
                                                                                                    Caused by: m.cno: 17: API: Phenotype.API is not available on this device. Connection failed with: cmc{statusCode=DEVELOPER_ERROR, resolution=null, message=null}
                                                                                                    	at m.cqp.a(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:13)
                                                                                                    	at m.coj.c(:com.google.android.gms.policy_maps_core_dynamite@234210309@234210304065.587101654.587101654:3)
                                                                                                    	... 10 more
2024-02-13 13:21:06.691  3070-3215  ProxyAndro...gerBackend com.example.mapdemo.gms              W  Too many Flogger logs received before configuration. Dropping old logs.
```

Tested on samsung A34 android 14 and play services 1 january 2024

**Comment by bernhard-fp** [comment]
I can confirm the warnings "ProxyAndro...gerBackend - Too many Flogger logs received before configuration. Dropping old logs." which occur very often on my app using gmaps sdk.
Pixel7 - Android 14.
Clearing the GooglePlayServices data, does not help.

**Comment by dkhawk** [comment]
This is a side effect of the maps SDK and no longer happen on updated Android devices.  Please reopen if updating does not resolve.
