### ISSUE TITLE
Certificate problem

### ISSUE THREAD

**Issue by JamalYounes** [googlemaps-samples/android-samples#1806]
Caused by: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target|#]
  at java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)|#]
  at java.base/sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:271)|#]
  at java.base/sun.security.validator.Validator.validate(Validator.java:256)|#]
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:230)|#]
  at java.base/sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:132)|#]
  at java.base/sun.security.ssl.CertificateMessage$T13CertificateConsumer.checkServerCerts(CertificateMessage.java:1302)|#]

**Comment by solomdeb** [comment]
java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)|

**Comment by JamalYounes** [comment]
> java.base/sun.security.validator.PKIXValidator.doBuild(PKIXValidator.java:388)|

Thank you for reply.
What can I do?

**Comment by JamalYounes** [comment]
please any one can help me???

**Comment by kikoso** [comment]
@JamalYounes , closing this issue. If it is related to the samples and you can reproduce it feel free to reopen and provide more information.
